Bump com.google.devtools.ksp from 2.0.0-1.0.23 to 2.0.10-1.0.24 (#23)
Bumps [com.google.devtools.ksp](https://github.com/google/ksp) from
2.0.0-1.0.23 to 2.0.10-1.0.24.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/google/ksp/releases">com.google.devtools.ksp's
releases</a>.</em></p>
<blockquote>
<h2>2.0.10-1.0.24</h2>
<h2>What's Changed</h2>
<ul>
<li>UPDATE_KOTLIN_VERSION: 2.0.10 by <a
href="https://github.com/ting-yuan"><code>@​ting-yuan</code></a> in <a
href="https://redirect.github.com/google/ksp/pull/2022">google/ksp#2022</a></li>
</ul>
<h2>2.0.10-RC2-1.0.24</h2>
<h2>What's Changed</h2>
<ul>
<li>UPDATE_KOTLIN_VERSION: 2.0.10-RC2 by <a
href="https://github.com/ting-yuan"><code>@​ting-yuan</code></a> in <a
href="https://redirect.github.com/google/ksp/pull/2017">google/ksp#2017</a></li>
</ul>
<p><strong>Full Changelog</strong>: <a
href="https://github.com/google/ksp/compare/2.0.0-1.0.24...2.0.10-RC2-1.0.24">https://github.com/google/ksp/compare/2.0.0-1.0.24...2.0.10-RC2-1.0.24</a></p>
<h2>2.0.10-RC-1.0.23</h2>
<p>KSP 1.0.23 for Kotlin 2.0.10-RC</p>
<h2>2.0.0-1.0.24</h2>
<h2>What's Changed</h2>
<p><a
href="https://redirect.github.com/google/ksp/issues/2013">#2013</a>
Handle edge cases of KtAnnotated.annotations
<a href="https://redirect.github.com/google/ksp/issues/2009">#2009</a>
Fix :kotlin-analysis-api:shadowJar failing on Windows
<a href="https://redirect.github.com/google/ksp/issues/2006">#2006</a>
Use symbol-processing-aa-embeddable in Gradle</p>
<h2>Bugs Fixed</h2>
<p><a
href="https://redirect.github.com/google/ksp/issues/1956">#1956</a>
IllegalAccessError in Dagger with KSP2.0.0-1.0.22 and KSP2
<a href="https://redirect.github.com/google/ksp/issues/1998">#1998</a>
KSP2 version 2.0.0-1.0.23 crashes on Moshi codegen with
NoSuchElementException: Collection contains no element matching the
predicate.</p>
<p><strong>Full Changelog</strong>: <a
href="https://github.com/google/ksp/compare/e8807446b16ba19e110cc23f6b852054614f7ec8...c63864cc1268bcb1c83e058494b6ff4b25947251">https://github.com/google/ksp/compare/e8807446b16ba19e110cc23f6b852054614f7ec8...c63864cc1268bcb1c83e058494b6ff4b25947251</a></p>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/google/ksp/commit/4e1f8cada900c76ae350dfe1175c898bba6e2aaf"><code>4e1f8ca</code></a>
Update CI to build for dedicated release branch</li>
<li><a
href="https://github.com/google/ksp/commit/b84edef59b6d37e2cc8d4f574a83764a1973bb7e"><code>b84edef</code></a>
UPDATE_KOTLIN_VERSION: 2.0.10</li>
<li><a
href="https://github.com/google/ksp/commit/7e600a0f94e3e9d2918a47d8ded708423b512162"><code>7e600a0</code></a>
UPDATE_KOTLIN_VERSION: 2.0.10-RC2</li>
<li><a
href="https://github.com/google/ksp/commit/c63864cc1268bcb1c83e058494b6ff4b25947251"><code>c63864c</code></a>
UPDATE_AA_VERSION: 2.1.0-dev-2499</li>
<li><a
href="https://github.com/google/ksp/commit/b683deeef999a0eeb2cf7c96226ad2f47a7cee73"><code>b683dee</code></a>
Handle edge cases of KtAnnotated.annotations</li>
<li><a
href="https://github.com/google/ksp/commit/27653c6300b7afed4f539b74d970cb9fdfa6c006"><code>27653c6</code></a>
Fix :kotlin-analysis-api:shadowJar failing on Windows</li>
<li><a
href="https://github.com/google/ksp/commit/e1b8468309aeff7912420a202300751783d0b2c9"><code>e1b8468</code></a>
Use symbol-processing-aa-embeddable in Gradle</li>
<li><a
href="https://github.com/google/ksp/commit/e8807446b16ba19e110cc23f6b852054614f7ec8"><code>e880744</code></a>
change android native targets for integration test until android sdk is
fixed</li>
<li><a
href="https://github.com/google/ksp/commit/9bacece1b3675874d1a7067bb52e3af25d49e5fd"><code>9bacece</code></a>
UPDATE_AA_VERSION: 2.1.0-dev-1329</li>
<li><a
href="https://github.com/google/ksp/commit/0c950e040eaea4921c234b2e26e8b70d4fddbe7f"><code>0c950e0</code></a>
set release branch to 1.0.24</li>
<li>Additional commits viewable in <a
href="https://github.com/google/ksp/compare/2.0.0-1.0.23...2.0.10-1.0.24">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=com.google.devtools.ksp&package-manager=gradle&previous-version=2.0.0-1.0.23&new-version=2.0.10-1.0.24)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>